### ISSUE TITLE
视频卡顿严重

### ISSUE THREAD

**Issue by liumeiyue** [Flowsnow/vedioStitching#1]
学长您好，小白学生麻烦您一下，硬件部分我直接用的海康高清视像头，出现严重卡顿现象。请问代码是不是不支持高清视频的采集？有没有调整分辨率的输入框操作？

**Comment by suncle1993** [comment]
高清视频本质还是每一帧的图片的分辨率高，在获取每一帧图像的时候可以调整分辨率的，你看下OpenCV对这一块的处理，顺便你的邮件我看到了，待会给你回复下

**Comment by liumeiyue** [comment]
嗯，谢谢学长指导！


| |
刘美月
|
|
18811335436@163.com
|
签名由网易邮箱大师定制
在2019年2月26日 12:01，Suncle Chen<notifications@github.com> 写道：

高清视频本质还是每一帧的图片的分辨率高，在获取每一帧图像的时候可以调整分辨率的，你看下OpenCV对这一块的处理，顺便你的邮件我看到了，待会给你回复下

**Comment by suncle1993** [comment]
你的三个问题回复如下：
1、摄像头的话是不是随便购买小钢炮摄像头即可，没有什么型号问题吧？
> 如果只是用于研究，摄像头随便买个差不多的就行。另外如果想要较少摄像头个数，你可以买广角摄像头或者鱼眼摄像头。而且清晰度不需要太高

2、摄像头买好之后，固定好，插接上电脑的USB即可是吗？
> 摄像头买好固定之后，插上电脑的usb不是随便插的，是有顺序的，这个需要你去实验，当然你也可以写一段摄像头标定程序来自动调整这个事情（这个在我以前的代码里是没有的），此外需要电脑有足够多的control之类的东西，你可以看下电脑的配置。（我在16年的时候做的经验是多数电脑都是不支持的，最好到老师的实验室找大型台式机，编码阶段就自己电脑就行）

3、采集卡是必要的是吗？
> 采集卡不是必须的。但是如果要做360度全景的，采集卡还是有用处的，主要是用来同步传输（应该是这样）

**Comment by liumeiyue** [comment]
收到，谢谢您的回复，以后还请多多指教！祝好！


| |
刘美月
|
|
18811335436@163.com
|
签名由网易邮箱大师定制
在2019年2月26日 12:09，Suncle Chen<notifications@github.com> 写道：

你的三个问题回复如下：
1、摄像头的话是不是随便购买小钢炮摄像头即可，没有什么型号问题吧？

如果只是用于研究，摄像头随便买个差不多的就行。另外如果想要较少摄像头个数，你可以买广角摄像头或者鱼眼摄像头。而且清晰度不需要太高

2、摄像头买好之后，固定好，插接上电脑的USB即可是吗？

摄像头买好固定之后，插上电脑的usb不是随便插的，是有顺序的，这个需要你去实验，当然你也可以写一段摄像头标定程序来自动调整这个事情（这个在我以前的代码里是没有的），此外需要电脑有足够多的control之类的东西，你可以看下电脑的配置。（我在16年的时候做的经验是多数电脑都是不支持的，最好到老师的实验室找大型台式机，编码阶段就自己电脑就行）

3、采集卡是必要的是吗？

采集卡不是必须的。但是如果要做360度全景的，采集卡还是有用处的，主要是用来同步传输（应该是这样）
