### ISSUE TITLE
360全景拼接

### ISSUE THREAD

**Issue by kankanjiuzou123** [Flowsnow/vedioStitching#2]
请问您有做360度全景拼接方面的工作吗？想请教些问题，主要是关于拼接速度方面的

**Comment by suncle1993** [comment]
毕业之后就没有做这方面的了，但是之前有同学做出了360度全景拼接的，都是：

> 标定 -> 计算拼接矩阵 -> 两两并行拼接

比如16个摄像头，提前开好并行

**Comment by kankanjiuzou123** [comment]
好的，谢谢，您说的并行拼接是指cuda并行加速吗？

**Comment by suncle1993** [comment]
> 好的，谢谢，您说的并行拼接是指cuda并行加速吗？

用你能想到的各种并行，CPU或者cuda等等，这个也取决于你的机器

**Comment by Cheri1748** [comment]
我想请教一下如何实现多目工业相机实时同步采集，项目和你这个类似
